apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone
  region: ap-southeast-1

iam:
  withOIDC: true

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
